### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by mohamed-moanis** [lucastan/uva-node#15]
I got that when setting it up with npm

/home/mohamed/uva-node/index.js:124
    var action = toks[0].toLowerCase();
                        ^
TypeError: Cannot read property 'toLowerCase' of undefined
    at executeLine (/home/mohamed/uva-node/index.js:124:25)
    at Interface.<anonymous> (/home/mohamed/uva-node/index.js:43:5)
    at Interface.emit (events.js:107:17)
    at Interface._onLine (readline.js:214:10)
    at Interface._line (readline.js:553:8)
    at Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
    at ReadStream.emit (events.js:110:17)
    at readline.js:1175:14
    at Array.forEach (native)

**Comment by mohamed-moanis** [comment]
that solved it
https://github.com/schkateboarder/uva-node/commit/d319e8195c973f1710b829ca6c9aeb24f9fb4a40

**Comment by lucastan** [comment]
thanks, i included it in https://github.com/lucastan/uva-node/commit/cdd32d87cf002b537d0c9f02601fb401cfbc908a
