### ISSUE TITLE
deprecated node-uuid@1.4.8 and error in biding.open

### ISSUE THREAD

**Issue by claudiosegala** [lucastan/uva-node#22]
receiving this warning when installing through npm!  
```Bash
root:~ segala$ npm install -g uva-node
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/uva -> /usr/local/lib/node_modules/uva-node/index.js
+ uva-node@0.1.11
updated 1 package in 6.163s
root:~ segala$ uva
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/Users/segala/.ssh/uva-node.key'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at createKey (/usr/local/lib/node_modules/uva-node/cryptoUtil.js:32:8)
    at getKey (/usr/local/lib/node_modules/uva-node/cryptoUtil.js:44:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/uva-node/cryptoUtil.js:50:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
root:~ segala$ 

```

**Comment by lucastan** [comment]
There is an error creating or opening the file. Please ensure you set the right permission for the .ssh folder. 

The warning should be harmless
