### ISSUE TITLE
Cannot use the command view

### ISSUE THREAD

**Issue by ShafquatMahbub** [lucastan/uva-node#24]
On my Ubuntu PC, I have to run uva-node as root, so when I use the command `view <problem nymber>` it shows 
`[12347:12347:0808/023756.187382:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`
and the command doesn't work. I set chromium-browser.
On the other hand trying to use uva-node without sudo shows
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/shafquat/.ssh/uva-node.key'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at createKey (/usr/local/lib/node_modules/uva-node/cryptoUtil.js:32:8)
    at getKey (/usr/local/lib/node_modules/uva-node/cryptoUtil.js:44:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/uva-node/cryptoUtil.js:50:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by lucastan** [comment]
You have to set the right permission to your .ssh directory.
