### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by vgautam-pt** [lucastan/uva-node#32]
> set-browser "/Applications/Firefox.app"
Browser set

> view 507
Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at cls.openBrowser (/usr/local/lib/node_modules/uva-node/app.js:260:22)
    at /usr/local/lib/node_modules/uva-node/index.js:206:25
    at /usr/local/lib/node_modules/uva-node/adapterUVA.js:287:21
    at fetchProbs (/usr/local/lib/node_modules/uva-node/adapterUVA.js:48:24)
    at cls.getProblemURL (/usr/local/lib/node_modules/uva-node/adapterUVA.js:278:13)
    at executeLine (/usr/local/lib/node_modules/uva-node/index.js:200:17)
    at Interface.<anonymous> (/usr/local/lib/node_modules/uva-node/index.js:43:5)

Platform macOS
---------------

> set-browser /Applications/Safari.app
Browser set

> view 507
Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at cls.openBrowser (/usr/local/lib/node_modules/uva-node/app.js:260:22)
    at /usr/local/lib/node_modules/uva-node/index.js:206:25
    at /usr/local/lib/node_modules/uva-node/adapterUVA.js:287:21
    at fetchProbs (/usr/local/lib/node_modules/uva-node/adapterUVA.js:48:24)
    at cls.getProblemURL (/usr/local/lib/node_modules/uva-node/adapterUVA.js:278:13)
    at executeLine (/usr/local/lib/node_modules/uva-node/index.js:200:17)
    at Interface.<anonymous> (/usr/local/lib/node_modules/uva-node/index.js:43:5)

**Comment by vgautam-pt** [comment]
Issue resolved by using

> set-browser "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
Browser set

> view 507
